export const USER_ROLE = {
  OWNER: 'OWNER',
  MANAGER: 'MANAGER',
  RECEPTIONIST: 'RECEPTIONIST',
  TRAINER: 'TRAINER'
};

export const MEMBER_STATUS = {
  ALL: 'ALL',
  ACTIVE: 'ACTIVE',
  EXPIRING_SOON: 'EXPIRING SOON',
  EXPIRED: 'EXPIRED',
  INACTIVE: 'INACTIVE'
};

export const MEMBERSHIP_STATUS = {
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
  FROZEN: 'FROZEN'
};

export const PERSONAL_TRAINING_STATUS = {
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
  PAUSED: 'PAUSED'
};

export const PLAN_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE'
};

export const DURATION_UNIT = {
  DAY: 'DAY',
  MONTH: 'MONTH',
  YEAR: 'YEAR'
};

export const PAYMENT_STATUS = {
  PAID: 'PAID',
  PARTIAL: 'PARTIAL',
  PENDING: 'PENDING',
  REFUNDED: 'REFUNDED'
};

export const PAYMENT_METHOD = {
  CASH: 'CASH',
  UPI: 'UPI',
  CARD: 'CARD',
  BANK_TRANSFER: 'BANK_TRANSFER'
};

export const ATTENDANCE_SOURCE = {
  FINGERPRINT: 'FINGERPRINT',
  MANUAL: 'MANUAL'
};

export const MESSAGE_CHANNEL = {
  WHATSAPP: 'WHATSAPP',
  EMAIL: 'EMAIL',
  SMS: 'SMS'
};

export const MESSAGE_STATUS = {
  QUEUED: 'QUEUED',
  SENT: 'SENT',
  DELIVERED: 'DELIVERED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
};

export const CAMPAIGN_STATUS = {
  DRAFT: 'DRAFT',
  QUEUED: 'QUEUED',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  COMPLETED_WITH_ERRORS: 'COMPLETED_WITH_ERRORS',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
};

export const RECIPIENT_TYPE = {
  SINGLE_MEMBER: 'SINGLE_MEMBER',
  SELECTED_MEMBERS: 'SELECTED_MEMBERS',
  ALL_ACTIVE: 'ALL_ACTIVE',
  ALL_MEMBERS: 'ALL_MEMBERS',
  EXPIRING_SOON: 'EXPIRING_SOON',
  EXPIRED: 'EXPIRED',
  PENDING_PAYMENT: 'PENDING_PAYMENT'
};

export const MESSAGE_TYPE = {
  EXPIRY_7_DAYS: 'EXPIRY_7_DAYS',
  EXPIRY_3_DAYS: 'EXPIRY_3_DAYS',
  EXPIRY_1_DAY: 'EXPIRY_1_DAY',
  MEMBERSHIP_EXPIRED: 'MEMBERSHIP_EXPIRED',
  GENERAL_ANNOUNCEMENT: 'GENERAL_ANNOUNCEMENT',
  PAYMENT_REMINDER: 'PAYMENT_REMINDER'
};

export const DEFAULT_REMINDER_DAYS = [7, 3, 1];

export const TEMPLATE_VARIABLES = [
  'memberName',
  'gymName',
  'membershipPlan',
  'expiryDate',
  'daysRemaining',
  'amountDue',
  'gymPhone'
];

export const GENDER_OPTIONS = ['Male', 'Female', 'Other'];

export const DURATION_UNITS = ['Days', 'Months', 'Years'];
