import { USER_ROLE } from './domain.js';

export const REPORT_TYPE = {
  GYM_OVERVIEW: 'GYM_OVERVIEW',
  REVENUE_COLLECTIONS: 'REVENUE_COLLECTIONS',
  MEMBERSHIP_PERFORMANCE: 'MEMBERSHIP_PERFORMANCE',
  DAILY_OPERATIONS: 'DAILY_OPERATIONS',
  YEARLY_SUMMARY: 'YEARLY_SUMMARY',
  MONTHLY_SUMMARY: 'MONTHLY_SUMMARY',
  YEAR_OVER_YEAR: 'YEAR_OVER_YEAR',
  MEMBER_GROWTH: 'MEMBER_GROWTH',
  MEMBER_ACTIVITY: 'MEMBER_ACTIVITY',
  MEMBER_RETENTION: 'MEMBER_RETENTION',
  MEMBER_ATTENDANCE: 'MEMBER_ATTENDANCE',
  MEMBERSHIP_EXPIRY: 'MEMBERSHIP_EXPIRY',
  OUTSTANDING_PAYMENTS: 'OUTSTANDING_PAYMENTS',
  ATTENDANCE_OVERVIEW: 'ATTENDANCE_OVERVIEW',
  ATTENDANCE_TRENDS: 'ATTENDANCE_TRENDS',
  PEAK_HOURS: 'PEAK_HOURS',
  DAILY_ATTENDANCE: 'DAILY_ATTENDANCE',
  TRAINER_PERFORMANCE: 'TRAINER_PERFORMANCE',
  TRAINER_MEMBER_ACTIVITY: 'TRAINER_MEMBER_ACTIVITY',
  PLAN_PERFORMANCE: 'PLAN_PERFORMANCE',
  PT_REVENUE: 'PT_REVENUE',
  PT_TRAINER_PERFORMANCE: 'PT_TRAINER_PERFORMANCE',
  PT_EXPIRY: 'PT_EXPIRY',
  PT_PLAN_PERFORMANCE: 'PT_PLAN_PERFORMANCE'
};

const ALL_STAFF = [USER_ROLE.OWNER, USER_ROLE.MANAGER, USER_ROLE.RECEPTIONIST];
const MEMBER_STAFF = [...ALL_STAFF, USER_ROLE.TRAINER];

export const REPORT_DEFINITIONS = [
  { category: 'BUSINESS', label: 'Gym Overview', value: REPORT_TYPE.GYM_OVERVIEW, roles: ALL_STAFF },
  { category: 'BUSINESS', label: 'Revenue & Collections', value: REPORT_TYPE.REVENUE_COLLECTIONS, roles: ALL_STAFF },
  { category: 'BUSINESS', label: 'Membership Performance', value: REPORT_TYPE.MEMBERSHIP_PERFORMANCE, roles: [USER_ROLE.OWNER, USER_ROLE.MANAGER] },
  { category: 'BUSINESS', label: 'Daily Operations', value: REPORT_TYPE.DAILY_OPERATIONS, roles: ALL_STAFF },
  { category: 'BUSINESS', label: 'Yearly Business Summary', value: REPORT_TYPE.YEARLY_SUMMARY, roles: [USER_ROLE.OWNER, USER_ROLE.MANAGER] },
  { category: 'BUSINESS', label: 'Monthly Business Summary', value: REPORT_TYPE.MONTHLY_SUMMARY, roles: [USER_ROLE.OWNER, USER_ROLE.MANAGER] },
  { category: 'BUSINESS', label: 'Year-over-Year', value: REPORT_TYPE.YEAR_OVER_YEAR, roles: [USER_ROLE.OWNER, USER_ROLE.MANAGER] },
  { category: 'MEMBERS', label: 'Member Growth', value: REPORT_TYPE.MEMBER_GROWTH, roles: ALL_STAFF },
  { category: 'MEMBERS', label: 'Member Activity', value: REPORT_TYPE.MEMBER_ACTIVITY, roles: MEMBER_STAFF },
  { category: 'MEMBERS', label: 'Member Retention', value: REPORT_TYPE.MEMBER_RETENTION, roles: [USER_ROLE.OWNER, USER_ROLE.MANAGER] },
  { category: 'MEMBERS', label: 'Member Attendance', value: REPORT_TYPE.MEMBER_ATTENDANCE, roles: MEMBER_STAFF },
  { category: 'MEMBERS', label: 'Membership Expiry', value: REPORT_TYPE.MEMBERSHIP_EXPIRY, roles: ALL_STAFF },
  { category: 'MEMBERS', label: 'Outstanding Payments', value: REPORT_TYPE.OUTSTANDING_PAYMENTS, roles: ALL_STAFF },
  { category: 'ATTENDANCE', label: 'Attendance Overview', value: REPORT_TYPE.ATTENDANCE_OVERVIEW, roles: MEMBER_STAFF },
  { category: 'ATTENDANCE', label: 'Attendance Trends', value: REPORT_TYPE.ATTENDANCE_TRENDS, roles: MEMBER_STAFF },
  { category: 'ATTENDANCE', label: 'Peak Hours', value: REPORT_TYPE.PEAK_HOURS, roles: MEMBER_STAFF },
  { category: 'ATTENDANCE', label: 'Daily Attendance', value: REPORT_TYPE.DAILY_ATTENDANCE, roles: MEMBER_STAFF },
  { category: 'TRAINERS', label: 'Trainer Performance', value: REPORT_TYPE.TRAINER_PERFORMANCE, roles: [USER_ROLE.OWNER, USER_ROLE.MANAGER] },
  { category: 'TRAINERS', label: 'Trainer Member Activity', value: REPORT_TYPE.TRAINER_MEMBER_ACTIVITY, roles: MEMBER_STAFF },
  { category: 'TRAINERS', label: 'PT Trainer Performance', value: REPORT_TYPE.PT_TRAINER_PERFORMANCE, roles: [USER_ROLE.OWNER, USER_ROLE.MANAGER] },
  { category: 'PERSONAL TRAINING', label: 'PT Revenue', value: REPORT_TYPE.PT_REVENUE, roles: [USER_ROLE.OWNER, USER_ROLE.MANAGER] },
  { category: 'PERSONAL TRAINING', label: 'PT Expiry', value: REPORT_TYPE.PT_EXPIRY, roles: ALL_STAFF },
  { category: 'PLANS', label: 'Membership Plan Performance', value: REPORT_TYPE.PLAN_PERFORMANCE, roles: [USER_ROLE.OWNER, USER_ROLE.MANAGER] },
  { category: 'PLANS', label: 'PT Plan Performance', value: REPORT_TYPE.PT_PLAN_PERFORMANCE, roles: [USER_ROLE.OWNER, USER_ROLE.MANAGER] }
];

export const DATE_RANGE = {
  TODAY: 'TODAY',
  YESTERDAY: 'YESTERDAY',
  THIS_WEEK: 'THIS_WEEK',
  LAST_WEEK: 'LAST_WEEK',
  THIS_MONTH: 'THIS_MONTH',
  LAST_MONTH: 'LAST_MONTH',
  THIS_QUARTER: 'THIS_QUARTER',
  LAST_QUARTER: 'LAST_QUARTER',
  THIS_YEAR: 'THIS_YEAR',
  LAST_YEAR: 'LAST_YEAR',
  CUSTOM: 'CUSTOM'
};

export const DATE_RANGE_OPTIONS = [
  ['Today', DATE_RANGE.TODAY], ['Yesterday', DATE_RANGE.YESTERDAY],
  ['This Week', DATE_RANGE.THIS_WEEK], ['Last Week', DATE_RANGE.LAST_WEEK],
  ['This Month', DATE_RANGE.THIS_MONTH], ['Last Month', DATE_RANGE.LAST_MONTH],
  ['This Quarter', DATE_RANGE.THIS_QUARTER], ['Last Quarter', DATE_RANGE.LAST_QUARTER],
  ['This Year', DATE_RANGE.THIS_YEAR], ['Last Year', DATE_RANGE.LAST_YEAR],
  ['Custom Range', DATE_RANGE.CUSTOM]
].map(([label, value]) => ({ label, value }));

export const ACTIVITY_THRESHOLDS = {
  HIGHLY_ACTIVE_VISITS_PER_WEEK: 4,
  ACTIVE_VISITS_PER_WEEK: 2,
  LOW_ACTIVITY_VISITS_PER_WEEK: 1,
  INACTIVE_DAYS: 10
};